#!/usr/bin/env python3
"""
 LMPC COMPLIANCE ENGINE (SIH26034) — NOTICE DRAFTING

 Since 01 May 2026 a FIRST contravention of s.36(1) is not a fine and not a prosecution
 — it is a warning with an IMPROVEMENT NOTICE under s.15(6). Drafting a show-cause notice
 for a first-time label defect is the wrong instrument.

 s.15(6) requires an improvement notice to do four things, and this module builds the
 document from those four requirements rather than from a fixed template:
   (a) state the grounds for believing the person has failed to comply;
   (b) specify the matters which constitute that failure;
   (c) specify the measures the person must take to secure compliance;
   (d) require those measures within a reasonable specified period.
 s.15(7): failure to comply -> registration suspended or revoked, after a hearing.
 s.50: appeal within 60 days.
"""

from __future__ import annotations
import datetime, hashlib
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

_root = Path(__file__).resolve().parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

try:
    import lmpc_rules as rules
except ImportError:
    try:
        import rule_table as rules
    except ImportError:
        from backend import rule_table as rules

DEFAULT_COMPLIANCE_DAYS = 30
DEFAULT_SHOW_CAUSE_DAYS = 15

DISCLAIMER = (
    "PROTOTYPE OUTPUT — generated by a decision-support tool built for Smart India "
    "Hackathon PS SIH26034. This is not an official Government of India communication "
    "and has no legal effect. It must be reviewed, corrected and signed by an authorised "
    "Legal Metrology Officer before service.")

_W = 86


def _rule_line(width: int = _W, ch: str = "=") -> str:
    return ch * width


def _wrap(text: str, width: int = _W, indent: str = "") -> List[str]:
    words, lines, cur = text.split(), [], indent
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = indent + w + " "
        else:
            cur += w + " "
    if cur.strip():
        lines.append(cur.rstrip())
    return lines


def evidence_fingerprint(payload: str) -> str:
    """
    SHA-256 over the audit record. Printing this on the notice lets the same finding be
    re-verified later — without it, a generated notice is unfalsifiable.
    """
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def select_instrument(failed_rule_ids: Sequence[str], offence_number: int = 1) -> str:
    if not failed_rule_ids:
        return "NONE"
    return rules.notice_kind_for(list(failed_rule_ids), offence_number)


def _header(title: str, ref: str, prepared_on: str, officer: str) -> List[str]:
    out = [_rule_line(), "*** D R A F T — N O T  I S S U E D ***".center(_W),
           title.center(_W), _rule_line(), ""]
    out += _wrap(DISCLAIMER)
    out += ["", _rule_line(ch="-"),
            f"Draft reference : {ref or '(assigned on issue)'}",
            f"Prepared on     : {prepared_on}",
            f"Prepared by     : {officer or '(officer name required before issue)'}",
            f"Rule table      : {rules.RULE_TABLE_VERSION}", ""]
    return out


def _subject_block(item: Dict) -> List[str]:
    return [
        "To,",
        f"M/s {item.get('manufacturer') or '(manufacturer / packer / importer to be identified)'}",
        "",
        f"Commodity       : {item.get('name', '-')}",
        f"Barcode / GTIN  : {item.get('barcode', '-')}",
        f"Evidence basis  : {item.get('data_source', 'not recorded')}",
        f"Evidence digest : {evidence_fingerprint(repr(sorted(item.get('checks', []), key=repr)))[:32]}",
        "",
    ]


def _footer(extra: Optional[List[str]] = None) -> List[str]:
    out = ["", "_____________________________",
           "Signature of authorised Legal Metrology Officer",
           "Designation / jurisdiction:"]
    if extra:
        out += [""] + extra
    out += ["", "(This draft carries no legal effect until signed and served.)", _rule_line()]
    return out


def draft_improvement_notice(item: Dict, failures: Sequence[Dict], officer_name: str = "",
                             ref: str = "", prepared_on: str = "",
                             compliance_days: int = DEFAULT_COMPLIANCE_DAYS) -> str:
    """
    Improvement notice under s.15(6). `failures` carries `rule_id` and `found`; citations,
    requirements and remedies come from the rule table, never from the caller.
    """
    prepared_on = prepared_on or datetime.datetime.now().strftime("%d-%B-%Y %H:%M")
    lines = _header("IMPROVEMENT NOTICE UNDER SECTION 15(6), LEGAL METROLOGY ACT, 2009",
                    ref, prepared_on, officer_name)
    lines += _subject_block(item)

    lines += _wrap(
        "WHEREAS on inspection of the above pre-packaged commodity there are grounds to "
        "believe that the requirements of section 18 of the Legal Metrology Act, 2009 "
        "read with Rule 6 of the Legal Metrology (Packaged Commodities) Rules, 2011 have "
        "not been complied with;")
    lines += ["", "(a) GROUNDS AND (b) MATTERS CONSTITUTING THE FAILURE:", ""]

    for i, f in enumerate(failures, 1):
        r = rules.rule(f["rule_id"])
        lines.append(f"  [{i}] {r.citation}")
        lines += _wrap(f"Requirement: {r.requirement}", indent="      ")
        lines.append(f"      Observed  : {f.get('found') or f.get('detail', '-')}")
        lines.append("")

    lines += ["(c) MEASURES REQUIRED TO SECURE COMPLIANCE:", ""]
    for i, f in enumerate(failures, 1):
        lines += _wrap(f"[{i}] {rules.rule(f['rule_id']).remedy}", indent="      ")
    lines.append("")

    lines += _wrap(
        f"(d) PERIOD FOR COMPLIANCE: you are required to take the measures specified "
        f"above within {compliance_days} days of service of this notice, and to report "
        f"compliance in writing to the undersigned within that period.")
    lines += [""]
    lines += _wrap(
        "CONSEQUENCE OF NON-COMPLIANCE: under section 15(7) of the Act, failure to comply "
        "with an improvement notice may result in the suspension or revocation of your "
        "registration or approval, after an opportunity of being heard. A subsequent "
        "contravention of the same provision attracts the penalties in the schedule below.")
    lines += ["", "  Escalation if the contravention recurs:"]

    seen = []
    for f in failures:
        r = rules.rule(f["rule_id"])
        if r.ladder.section in seen:
            continue
        seen.append(r.ladder.section)
        lines.append(f"    {r.ladder.section}")
        lines.append(f"      Second contravention     : {r.ladder.at(2).describe()}")
        lines.append(f"      Third or subsequent      : {r.ladder.at(3).describe()}")
    lines.append("")
    lines += _wrap("APPEAL: an appeal against this notice lies under section 50 of the Act "
                   "within 60 days of the date of service.")
    lines += _footer()
    return "\n".join(lines)


def draft_show_cause_notice(item: Dict, failures: Sequence[Dict], officer_name: str = "",
                            ref: str = "", prepared_on: str = "", offence_number: int = 2,
                            reply_days: int = DEFAULT_SHOW_CAUSE_DAYS) -> str:
    """
    For a repeat contravention, or one that remained criminal after Jan Vishwas 2026
    (notably short measure under s.36(2)).
    """
    prepared_on = prepared_on or datetime.datetime.now().strftime("%d-%B-%Y %H:%M")
    lines = _header("SHOW CAUSE NOTICE — LEGAL METROLOGY ACT, 2009", ref, prepared_on,
                    officer_name)
    lines += _subject_block(item)
    lines.append(f"Recorded as contravention number {offence_number} for this addressee.")
    lines.append("")
    lines += _wrap(
        "WHEREAS on inspection the following contraventions of the Legal Metrology Act, "
        "2009 and the Legal Metrology (Packaged Commodities) Rules, 2011 were recorded:")
    lines.append("")

    for i, f in enumerate(failures, 1):
        r = rules.rule(f["rule_id"])
        c = r.ladder.at(offence_number)
        lines.append(f"  [{i}] {r.citation}")
        lines.append(f"      Obligation : {r.obligation_section}")
        lines.append(f"      Enforcement: {r.ladder.section}")
        lines.append(f"      Observed   : {f.get('found') or f.get('detail', '-')}")
        lines += _wrap(f"Liability  : {c.describe()}", indent="      ")
        if r.amendment_note:
            lines += _wrap(f"Note: {r.amendment_note}", indent="      ")
        lines.append("")

    lines += _wrap(
        f"NOW THEREFORE you are called upon to show cause in writing within {reply_days} "
        f"days of service of this notice as to why action should not be taken in respect "
        f"of the contraventions set out above.")
    lines += [""]
    lines += _wrap(
        "COMPOUNDING: the offences set out above may be compoundable under section 48 of "
        "the Act. The compounding amount may not exceed the maximum fine imposable for "
        "the offence compounded.")
    lines += [""]
    lines += _wrap(
        "NOTE FOR THE REVIEWING OFFICER: the liabilities stated above are drawn from the "
        f"rule table version {rules.RULE_TABLE_VERSION}, verified against "
        f"{rules.RULE_TABLE_VERIFIED_AGAINST} Confirm the offence count for this "
        "addressee against the enforcement register before service, since the liability "
        "depends on it.")
    lines += _wrap("APPEAL: section 50, within 60 days of service.")
    lines += _footer()
    return "\n".join(lines)


def draft_notice(item: Dict, failures: Sequence[Dict], officer_name: str = "",
                 ref: str = "", prepared_on: str = "", offence_number: int = 1) -> Dict:
    """
    Single entry point. Chooses the instrument, builds it, and reports which was chosen
    and why — the UI should show that reasoning rather than hiding it.
    """
    ids = [f["rule_id"] for f in failures]
    instrument = select_instrument(ids, offence_number)

    if instrument == "NONE":
        return {"instrument": "NONE", "text": "",
                "reason": "No contravention was recorded, so no notice arises."}

    if instrument == rules.IMPROVEMENT_NOTICE:
        return {
            "instrument": rules.IMPROVEMENT_NOTICE,
            "text": draft_improvement_notice(item, failures, officer_name, ref, prepared_on),
            "reason": ("Every recorded contravention is a first contravention of a provision "
                       "for which section 15(6) prescribes a warning with an improvement "
                       "notice. Since 01 May 2026 no monetary penalty arises at this stage, "
                       "so a show-cause notice would be the wrong instrument."),
        }

    criminal = [rules.rule(i).id for i in ids
                if rules.consequence_for(i, offence_number).kind == rules.CRIMINAL_FINE]
    reason = (f"Recorded as contravention number {offence_number}, which is past the "
              f"improvement-notice stage.") if offence_number > 1 else (
        "One or more contraventions remained criminal after the Jan Vishwas amendments "
        f"({', '.join(criminal)}), so the improvement-notice route does not apply.")

    return {"instrument": "SHOW_CAUSE",
            "text": draft_show_cause_notice(item, failures, officer_name, ref, prepared_on,
                                            offence_number),
            "reason": reason}
