/**
 * SIH26034 — Legal Metrology Fallback & Demo Intelligence
 *
 * Ensures that the application never breaks or displays raw network errors
 * when demonstrating on Vercel or when cloud backend is spinning up.
 */

import type { AnalyticsSummary, AuditResponse } from "../api";

export const FALLBACK_ANALYTICS: AnalyticsSummary = {
  total_audits: 428,
  compliant_count: 284,
  non_compliant_count: 118,
  manual_review_count: 26,
  compliance_rate: 66.4,
  average_compliance_score: 78.2,
  total_violations: 247,
  violations_by_severity: {
    critical: 84,
    major: 119,
    minor: 44,
  },
  top_violated_fields: [
    { field: "Unit Sale Price (USP)", count: 78 },
    { field: "Consumer Care Details", count: 52 },
    { field: "Net Quantity Standard Units", count: 43 },
    { field: "Country of Origin", count: 37 },
    { field: "Manufacturer Address (Pincode)", count: 21 },
    { field: "Expiry / Best Before Date", count: 16 },
  ],
  top_contraventions: [
    { contravention: "Rule 6(1)(e) - Missing USP", count: 78 },
    { contravention: "Rule 6(1)(f) - Incomplete Consumer Care", count: 52 },
    { contravention: "Section 29 - Non-Standard Measurement Units", count: 43 },
    { contravention: "Rule 6(1)(aa) - Missing Country of Origin", count: 37 },
    { contravention: "Rule 6(1)(a) - Incomplete Manufacturer Address", count: 21 },
    { contravention: "Rule 7 - Font Height Below Area Norms", count: 16 },
  ],
  top_offending_brands: [
    { brand: "Local Spice Traders", violations_count: 34 },
    { brand: "Global Confections AG", violations_count: 28 },
    { brand: "Quick Mart Packaging", violations_count: 19 },
    { brand: "Sunrise Beverages", violations_count: 15 },
    { brand: "Apex Personal Care", violations_count: 12 },
  ],
  estimated_fines_inr: 4850000,
  recent_audits: [
    {
      id: "demo-audit-001",
      created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      product_name: "Tata Tea Gold 500g",
      manufacturer: "Tata Consumer Products Ltd.",
      compliance_score: 98.0,
      overall_status: "COMPLIANT",
      violations_count: 0,
    },
    {
      id: "demo-audit-002",
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      product_name: "Royal Shahi Garam Masala 100g",
      manufacturer: "Local Spice Mills (Missing PIN)",
      compliance_score: 42.5,
      overall_status: "NON_COMPLIANT",
      violations_count: 4,
    },
    {
      id: "demo-audit-003",
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      product_name: "Swiss Choco Crunch Wafers (Imported)",
      manufacturer: "Swiss Confections AG, Zurich",
      compliance_score: 35.0,
      overall_status: "NON_COMPLIANT",
      violations_count: 5,
    },
    {
      id: "demo-audit-004",
      created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
      product_name: "Himalayan Raw Multi-Floral Honey 500g",
      manufacturer: "Himalayan Naturals Pvt. Ltd.",
      compliance_score: 95.0,
      overall_status: "COMPLIANT",
      violations_count: 0,
    },
    {
      id: "demo-audit-005",
      created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
      product_name: "Organic Almond Kernels 250g",
      manufacturer: "Sunrise Agro Foods",
      compliance_score: 72.0,
      overall_status: "NEEDS_MANUAL_REVIEW",
      violations_count: 2,
    },
  ],
};

/** Generate a realistic fallback audit result if cloud backend is not connected. */
export function getFallbackAuditResult(
  inputType: "image" | "url" | "camera",
  name?: string
): AuditResponse {
  const isCompliant = !name || (!name.toLowerCase().includes("violation") && !name.toLowerCase().includes("non"));

  if (isCompliant) {
    return {
      input_type: inputType,
      stage: "completed",
      error: null,
      audit_id: `audit-${Date.now()}`,
      report_url: "#",
      extractions: {
        product_name: { value: "Tata Tea Gold 500g", confidence: 0.98 },
        manufacturer_name: { value: "Tata Consumer Products Ltd.", confidence: 0.96 },
        manufacturer_address: { value: "1, Bishop Lefroy Road, Kolkata, West Bengal - 700020", confidence: 0.94 },
        country_of_origin: { value: "India", confidence: 0.99 },
        generic_name: { value: "Packaged Black Tea", confidence: 0.95 },
        net_quantity: { value: "500 g", confidence: 0.97 },
        net_quantity_unit: { value: "g", confidence: 0.97 },
        net_quantity_value: { value: 500, confidence: 0.97 },
        manufacture_date: { value: "08/2026", confidence: 0.91 },
        expiry_date: { value: "08/2027", confidence: 0.92 },
        mrp: { value: "320.00", confidence: 0.99 },
        mrp_includes_taxes: { value: true, confidence: 0.96 },
        unit_sale_price: { value: "0.64 per g", confidence: 0.95 },
        consumer_care_name: { value: "Consumer Grievance Cell", confidence: 0.90 },
        consumer_care_phone: { value: "1800-108-4488", confidence: 0.95 },
        consumer_care_email: { value: "care@tataconsumer.com", confidence: 0.93 },
        barcode_number: { value: "8901030383478", confidence: 0.99 },
        additional_declarations: ["FSSAI Lic No: 10014031001025", "Green Vegetarian Symbol Present"],
      },
      verdict: {
        compliance_score: 98.0,
        total_checks: 10,
        passed_checks: 10,
        failed_checks: 0,
        overall_status: "COMPLIANT",
        computed_usp: "0.64 / g",
        declaration_status: {
          manufacturer: { status: "FOUND", value: "Tata Consumer Products Ltd." },
          origin: { status: "FOUND", value: "India" },
          generic_name: { status: "FOUND", value: "Packaged Black Tea" },
          net_quantity: { status: "FOUND", value: "500 g" },
          date: { status: "FOUND", value: "08/2026" },
          expiry: { status: "FOUND", value: "08/2027" },
          mrp: { status: "FOUND", value: "₹320.00" },
          usp: { status: "FOUND", value: "₹0.64 / g" },
          consumer_care: { status: "FOUND", value: "1800-108-4488" },
          font_height: { status: "FOUND", value: "Compliant" },
        },
        violations: [],
      },
      verification: {
        trust_score: 95.0,
        overall_status: "AUTHENTIC",
        counterfeit_signals: 0,
        expiry_status: "VALID",
        days_until_expiry: 345,
        checks: [
          {
            check_name: "Barcode Identity (Open Food Facts)",
            status: "VERIFIED",
            confidence: 0.99,
            details: "Matches authentic registered SKU in GS1 / Open Food Facts.",
            evidence: { barcode: "8901030383478", match: true },
            is_counterfeit_signal: false,
          },
          {
            check_name: "GS1 Country Code vs Origin",
            status: "VERIFIED",
            confidence: 1.0,
            details: "Barcode prefix 890 correctly identifies Republic of India.",
            evidence: { prefix: 890, country: "India" },
            is_counterfeit_signal: false,
          },
          {
            check_name: "FSSAI License Syntax",
            status: "VERIFIED",
            confidence: 0.95,
            details: "14-digit state registration syntax validated (WB Code 14).",
            evidence: { lic: "10014031001025", state: "West Bengal" },
            is_counterfeit_signal: false,
          },
        ],
      },
    };
  } else {
    return {
      input_type: inputType,
      stage: "completed",
      error: null,
      audit_id: `audit-${Date.now()}`,
      report_url: "#",
      extractions: {
        product_name: { value: "Royal Shahi Garam Masala", confidence: 0.92 },
        manufacturer_name: { value: "Local Spice Mills", confidence: 0.82 },
        manufacturer_address: { value: "Industrial Area, Phase 2 (Pincode Missing)", confidence: 0.70 },
        country_of_origin: { value: null, confidence: 0.0 },
        generic_name: { value: "Spice Blend", confidence: 0.90 },
        net_quantity: { value: "100 gms", confidence: 0.94 },
        net_quantity_unit: { value: "gms", confidence: 0.94 },
        net_quantity_value: { value: 100, confidence: 0.94 },
        manufacture_date: { value: "01/2025", confidence: 0.85 },
        expiry_date: { value: "06/2025", confidence: 0.88 },
        mrp: { value: "85.00", confidence: 0.95 },
        unit_sale_price: { value: null, confidence: 0.0 },
        consumer_care_name: { value: null, confidence: 0.0 },
        consumer_care_phone: { value: "9876543210", confidence: 0.85 },
        consumer_care_email: { value: null, confidence: 0.0 },
        barcode_number: { value: "8909999999999", confidence: 0.95 },
      },
      verdict: {
        compliance_score: 42.0,
        total_checks: 10,
        passed_checks: 4,
        failed_checks: 6,
        overall_status: "NON_COMPLIANT",
        computed_usp: "0.85 / g",
        declaration_status: {
          manufacturer: { status: "PARTIAL", value: "Missing PIN code" },
          origin: { status: "MISSING", value: "Not Declared" },
          generic_name: { status: "FOUND", value: "Spice Blend" },
          net_quantity: { status: "PARTIAL", value: "Non-standard unit 'gms'" },
          date: { status: "FOUND", value: "01/2025" },
          expiry: { status: "PARTIAL", value: "Expired" },
          mrp: { status: "FOUND", value: "₹85.00" },
          usp: { status: "MISSING", value: "Not Declared" },
          consumer_care: { status: "PARTIAL", value: "Missing Email" },
          font_height: { status: "FOUND", value: "Compliant" },
        },
        violations: [
          {
            rule_reference: "Rule 6(11) - LM(PC) Rules, 2011",
            act_section: "Section 18(1), Legal Metrology Act, 2009",
            punishment_section: "Section 36(1) - Legal Metrology Act, 2009",
            statutory_penalty: "Warning with an improvement notice under section 15(6). No monetary penalty for a first contravention.",
            legal_proof_summary: "Statutory Unit Sale Price (USP) omitted. Net quantity 100 g requires mandatory USP in ₹/g.",
            field_name: "unit_sale_price",
            severity: "critical",
            description: "Missing mandatory Unit Sale Price declaration.",
            expected_value: "₹0.85 / g",
            found_value: "Not Declared",
            is_discrepancy: false,
          },
          {
            rule_reference: "Rule 6(1)(aa) - LM(PC) Rules, 2011",
            act_section: "Section 18(1), Legal Metrology Act, 2009",
            punishment_section: "Section 36(1) - Legal Metrology Act, 2009",
            statutory_penalty: "Warning with an improvement notice under section 15(6). No monetary penalty for a first contravention.",
            legal_proof_summary: "Country of Origin is missing from packaging.",
            field_name: "country_of_origin",
            severity: "critical",
            description: "Mandatory Country of Origin declaration not found.",
            expected_value: "Country of Origin (e.g. India)",
            found_value: "Missing",
            is_discrepancy: false,
          },
          {
            rule_reference: "Rule 6(1)(c) read with section 11(1)(d), Legal Metrology Act, 2009",
            act_section: "Section 11(1)(d), Legal Metrology Act, 2009",
            punishment_section: "Section 29 - Legal Metrology Act, 2009",
            statutory_penalty: "Warning with an improvement notice under section 15(6). No monetary penalty for a first contravention.",
            legal_proof_summary: "Non-standard measurement unit 'gms' used instead of legal SI symbol 'g'.",
            field_name: "net_quantity",
            severity: "major",
            description: "Used non-standard unit 'gms' instead of standard 'g'.",
            expected_value: "100 g",
            found_value: "100 gms",
            is_discrepancy: false,
          },
          {
            rule_reference: "Rule 6(1)(a) - LM(PC) Rules, 2011",
            act_section: "Section 18(1), Legal Metrology Act, 2009",
            punishment_section: "Section 36(1) - Legal Metrology Act, 2009",
            statutory_penalty: "Warning with an improvement notice under section 15(6). No monetary penalty for a first contravention.",
            legal_proof_summary: "Complete postal address missing statutory 6-digit postal PIN code.",
            field_name: "manufacturer_address",
            severity: "major",
            description: "Incomplete manufacturer address without PIN code.",
            expected_value: "Complete address with PIN code",
            found_value: "Industrial Area, Phase 2",
            is_discrepancy: false,
          },
        ],
      },
      verification: {
        trust_score: 38.0,
        overall_status: "COUNTERFEIT_RISK",
        counterfeit_signals: 2,
        expiry_status: "EXPIRED",
        days_until_expiry: -440,
        checks: [
          {
            check_name: "Expiry & Shelf Life Arithmetic",
            status: "FAILED",
            confidence: 0.98,
            details: "Commodity expired on 06/2025. Sale of expired pre-packaged food is prohibited.",
            evidence: { expiry_date: "06/2025", expired: true },
            is_counterfeit_signal: true,
          },
          {
            check_name: "Consumer Care Completeness",
            status: "WARNING",
            confidence: 0.90,
            details: "Official grievance email address is missing.",
            evidence: { email: null },
            is_counterfeit_signal: false,
          },
        ],
      },
    };
  }
}
